#!/system/bin/sh

if [ -e /system/xmister/soundfix ]
then
    echo "--- Applied: soundfix";
    cat /system/xmister/soundfix > /proc/xmister/soundfix
fi

if [ -e /system/xmister/undervolt ]
then
    echo "--- Applied: undervolt";
    cat /system/xmister/undervolt > /proc/xmister/undervolt
fi

if [ -e /system/xmister/buffer ]
then
    echo "--- Applied: buffer";
    cat /system/xmister/buffer > /proc/xmister/buffer
fi
